### ISSUE TITLE
xahaud installation error

### ISSUE THREAD

**Issue by mihaltsov84** [Xahau/mainnet-docker#3]
When executing "./build" I encountered a number of errors. Help me understand how to fix them? (Screenshots attached in file)
Thank you!
![Screenshot_20240222_121829_Termius](https://github.com/Xahau/mainnet-docker/assets/18306021/309fc8ae-3ec6-4b9a-83b2-6cc34cea61d5)
![Screenshot_20240222_121855_Termius](https://github.com/Xahau/mainnet-docker/assets/18306021/7d231aed-1509-4e3a-a65d-ce78c0c0e6a9)
![Screenshot_20240222_121923_Termius](https://github.com/Xahau/mainnet-docker/assets/18306021/89fc9bd6-7026-4f5d-afe6-a9c615635c7f)

**Comment by WietseWind** [comment]
Can you add some details about your build environment?

**Comment by mihaltsov84** [comment]
What exactly do I need to do, I'm a noob but learnable

**Comment by mihaltsov84** [comment]
If I understood correctly then: v12.22.9

**Comment by WietseWind** [comment]
> What exactly do I need to do, I'm a noob but learnable

OS (distro, version, ...), CPU architecture, ...

By the way: the errors in your screenshots are perfectly fine, expected :) End of messages show your next steps :)

**Comment by mihaltsov84** [comment]
OC: Ubuntu 22.04; 24GB RAM 250GB NVME Disk 12 Dedicated vCPUs AMD EPYC Processors 10Gbit/s Network
![Screenshot_20240222_134818_Termius](https://github.com/Xahau/mainnet-docker/assets/18306021/c774d5a0-8339-4727-ba77-bd7d096f2137)
![Screenshot_20240222_134654_Termius](https://github.com/Xahau/mainnet-docker/assets/18306021/ca7af5d4-15b4-41c5-a477-5e78b9618513)
If I missed something, I can check with support for other information.

**Comment by mihaltsov84** [comment]
> Кстати: ошибки на ваших скриншотах вполне ожидаемы :) В конце сообщений показаны ваши дальнейшие действия :)

Since I’m new to this, I’m a little stupid, but for example, I figured out “evernode” and here I should

**Comment by WietseWind** [comment]
The errors in your screenshots are perfectly fine, expected :) End of messages show your next steps :)

**Comment by mihaltsov84** [comment]
No matter what I tried (ChatGPT helped), nothing works, always the same errors. I'm desperate

**Comment by WietseWind** [comment]
> The errors in your screenshots are perfectly fine, expected :) End of messages show your next steps :)

The errors in your screenshots are perfectly fine, expected :) End of messages show your next steps :)

**Comment by mihaltsov84** [comment]
I am running the command "sudo apt-get update"
"sudo apt-get upgrade" then ./build again and it still prompts me to update the packages. If I enter ./up it displays the message "Failed to read '"/etc/opt/xahau/xahaud.cfg"'.2: No such file or directory"
![Screenshot_20240224_014209_Termius](https://github.com/Xahau/mainnet-docker/assets/18306021/6503835e-18f3-45da-9ab6-897055b7c268)

**Comment by WietseWind** [comment]
Ah sorry I thought you meant the build errors.

I understand.

Problem is it's only running with the sample config. I'll change the code to handle that. There will be an update in a minute.

**Comment by WietseWind** [comment]
Thanks for your patience 🤗 

I just fixed this in: https://github.com/Xahau/mainnet-docker/commit/15afcad3ed1486c100ec6eb873e630d9f8b38cf3

If you `git pull` and run `up` again you should be good :)

**Comment by mihaltsov84** [comment]
Everything worked out)) but I still have a question: there is an error in the screenshot, is this normal or does something need to be done.
![Screenshot_20240224_031158_Termius](https://github.com/Xahau/mainnet-docker/assets/18306021/35c060a7-4aaf-4cc4-92fe-a3e2548694ee)

**Comment by mihaltsov84** [comment]
> Thanks for your patience 🤗
> 
> I just fixed this in: [15afcad](https://github.com/Xahau/mainnet-docker/commit/15afcad3ed1486c100ec6eb873e630d9f8b38cf3)
> 
> If you `git pull` and run `up` again you should be good :)

Everything is working! Connected the first Evernode to my node. Thank you so much for taking the time to answer.🫡

**Comment by WietseWind** [comment]
Yay, great to hear! And thanks for reporting!

**Comment by mihaltsov84** [comment]
I just got this error, what does it mean and how can I fix it?
![Screenshot_20240309_160050_Termius.jpg](https://github.com/Xahau/mainnet-docker/assets/18306021/9e5e70b5-298d-40c9-8dd8-033142256622)


![Screenshot_20240309_161828_Termius.jpg](https://github.com/Xahau/mainnet-docker/assets/18306021/7fb6f82e-5b19-45b8-9c4b-01f34d71781b)
